# Используем образ Node.js
FROM node:16.14

# Устанавливаем директорию приложения в контейнере
WORKDIR /project/sub_app
RUN npm install -g npm@9.8.1
RUN npm install -g ganache-cli
RUN npm install -g truffle
# Копируем зависимости и файлы пакета
#COPY package*.json ./

# Устанавливаем зависимости
#RUN yarn install

# Копируем остальные файлы приложения
#COPY . .

# Запускаем команду для старта приложения
#CMD ["yarn", "start"]
