# Copyright 2020 DGT NETWORK INC © Stanislav Parsov
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# docker build -f docker/Dockerfile -t dgt-common-jammy

# -------------===  build ===-------------

FROM ubuntu:jammy
ARG DGT_TOP
#RUN apt-get update && apt-get install gnupg -y

# git python3-stdeb net-tools pkg-config
RUN apt-get update && apt-get install --no-install-recommends -y -q \
    iputils-ping \
    unzip         \
    openssl

RUN apt-get install --no-install-recommends -y -q \
    python3       \
    python3-pip   \
    python3-grpcio \
    python3-protobuf 
    

RUN apt-get install --no-install-recommends -y -q \
    python3-cbor \
    python3-colorlog \
    python3-cryptography>=1.7.1 \
    python3-dev \
    python3-lmdb \
    python3-netifaces \
    python3-toml \
    python3-yaml \
    python3-zmq \
    python3-requests \
    python3-sha3 \
    && rm -rf /var/lib/apt/lists/*
     
      
#  python3-graphviz libssl-dev
RUN pip3 install secp256k1
RUN pip3 install grpcio-tools
RUN pip3 install pyformance
RUN pip3 install chardet
RUN pip3 install cookiecutter
RUN pip3 install fastapi
RUN pip3 install pydantic pydantic-settings
RUN pip3 install sqlalchemy
RUN pip3 install sqlalchemy_utils
RUN pip3 install jwt
RUN pip3 install alembic
RUN pip3 install uvicorn
RUN pip3 install common
RUN pip3 install email-validator
RUN pip3 install environs
#RUN pip3 install asyncpg # postgress
RUN pip3 install passlib
RUN pip3 install aiosqlite
RUN pip3 install python-multipart
#RUN pip3 install kombu
#RUN pip3 install openpyxl
#RUN pip3 install databases
#RUN pip3 install aiomysql
#RUN pip3 install pymysql
RUN pip3 install fastapi_pagination
RUN pip3 install python-jose
RUN pip3 install slowapi
ENV PATH=$PATH:/project/$DGT_TOP/bin:

RUN ln -s /usr/bin/python3 /usr/bin/python

#RUN mkdir -p /etc/dgt/keys
#RUN mkdir -p /var/lib/dgt
#RUN mkdir -p /var/log/dgt

WORKDIR /project/$DGT_TOP

CMD echo "\033[0;32m--- Building FAST-API ---\n\033[0m" 
