# Пример конфигурации nginx.conf

user  nginx;
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    #error_log /var/log/nginx/ssl_error.log debug;
    upstream backend_dgt {
        server api-dgt-c1-1:8108;
    }
    upstream fast_dgt {
      server fast-api-dgt-c1-1:8008;
    }

    server {
        listen 8880;
        server_name localhost;
        #location /api/ {
        #   proxy_pass http://kamaz-heat:8900/api/; # Проксирование на Django бэкенд
           # Другие настройки для бэкенда (например, прокси-буффер и другие)
        #}
        
        location ~ ^/(transactions|state|blocks|batches|batch_statuses|validator|run_statuses|run)$ { # ~ ^/(transactions|state)$
           #proxy_pass http://api-dgt-c1-1:8108;
           proxy_pass http://backend_dgt$request_uri;
           proxy_set_header X-Forwarded-Proto $scheme;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header Host $host;
           proxy_redirect off;
        }
        location ~ ^/(tx_families|topology|receipts|peers|nodes)$ { 
           proxy_pass http://backend_dgt$request_uri;
        }
        location /dag/ { # ~ ^/(transactions|state)$
           #proxy_pass http://api-dgt-c1-1:8108;
           proxy_pass http://backend_dgt$request_uri;
        }
        location /dapi/ {
          rewrite ^/dapi/(.*) /$1 break;
          proxy_pass http://backend_dgt;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/ {
          #rewrite ^/api/(.*) /$1 break;
          proxy_pass http://fast_dgt/api/v1/;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Port $server_port;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Original-URI $request_uri;
        }
        location / {
            add_header 'Access-Control-Allow-Origin' '*';
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri /index.html;
        }
        #location ~* ^/(?<token>[^/]+)/password-entry$ {
        #return 301 $scheme://$host:$server_port/;
        #}
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            add_header 'Access-Control-Allow-Origin' '*';
            root   /usr/share/nginx/html;
        }
    }
}

