# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stuff_common/protobuf/smart_stuff_token.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-stuff_common/protobuf/smart_stuff_token.proto\"b\n\x0eStuffTokenInfo\x12\x12\n\ngroup_code\x18\x01 \x01(\t\x12\x11\n\towner_key\x18\x02 \x01(\t\x12\x0c\n\x04sign\x18\x03 \x01(\t\x12\x0c\n\x04user\x18\x04 \x01(\t\x12\r\n\x05stuff\x18\x05 \x01(\x0c\x42\x1c\n\x18sawtooth.config.protobufP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stuff_common.protobuf.smart_stuff_token_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030sawtooth.config.protobufP\001'
  _STUFFTOKENINFO._serialized_start=49
  _STUFFTOKENINFO._serialized_end=147
# @@protoc_insertion_point(module_scope)
