# 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -------------===  build ===-------------

FROM ubuntu:jammy
FROM python:3 as python-base
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_NO_INTERACTION=1 \
    PYSETUP_PATH="/opt/pysetup" \
    VENV_PATH="/opt/pysetup/.venv"

RUN apt-get update && apt -y upgrade\
 && apt-get install gnupg -y

RUN apt-get install  --no-install-recommends -y \
    build-essential \
    cron coreutils  procps

RUN apt-get install -y -q \
    git apt-utils \
    iputils-ping\
    net-tools curl gcc autoconf cmake libtool 
      
RUN apt-get install -y -q \ 
    python3-pip \                                                            
    python3-aiodns \                                                                    
    python3-aiohttp  \                                          
    python3-colorlog \                                                                  
    python3-cchardet\                                                                   
    python3-pyformance \                                                                
    python3-toml \                                                                      
    python3-yaml \                                                                      
    python3-zmq python3-cbor python3-secp256k1 python3-cryptography>=1.7.1              
											
RUN python3 -V      

#python3-aiohttp-security
ENV PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH"
RUN pip install pysha3
RUN pip install aiohttp_security[session]
RUN mkdir /var/log/sawtooth

ENV PATH=$PATH:/project/$DGT_TOP/bin:

WORKDIR /project/$DGT_TOP

CMD echo "\033[0;32m--- Building dgt-dashboard ---\n\033[0m" \
 && bin/protogen \
 && cd dashboard \
 && python3 setup.py clean --all \
 && python3 setup.py build






