version: '3.6'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-dgt
    ports:
      - "8880:8880"
    volumes:
      - ../etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../dash/nginx/html:/usr/share/nginx/html
      - ../dash/nginx/cert:/usr/share/nginx/cert
    networks:
    - network1
 


networks:
  network1:
     name: dgt-net
