version: '3.6'

services:
  nginx-dgt:
    image: nginx:latest
    container_name: nginx-dgt
    ports:
      - "8888:8888"
    volumes:
      - ../etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../x-dgt/html:/usr/share/nginx/html
      - ../x-dgt/cert:/usr/share/nginx/cert
    networks:
    - network1
 


networks:
  network1:
     name: dgt1-network
