# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bgt_common/protobuf/smart_bgt_token.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bgt_common/protobuf/smart_bgt_token.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\030sawtooth.config.protobufP\001'),
  serialized_pb=_b('\n)bgt_common/protobuf/smart_bgt_token.proto\"U\n\x0c\x42gtTokenInfo\x12\x12\n\ngroup_code\x18\x01 \x01(\t\x12\x11\n\towner_key\x18\x02 \x01(\t\x12\x0c\n\x04sign\x18\x03 \x01(\t\x12\x10\n\x08\x64\x65\x63imals\x18\x04 \x01(\rB\x1c\n\x18sawtooth.config.protobufP\x01\x62\x06proto3')
)




_BGTTOKENINFO = _descriptor.Descriptor(
  name='BgtTokenInfo',
  full_name='BgtTokenInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_code', full_name='BgtTokenInfo.group_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner_key', full_name='BgtTokenInfo.owner_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sign', full_name='BgtTokenInfo.sign', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decimals', full_name='BgtTokenInfo.decimals', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['BgtTokenInfo'] = _BGTTOKENINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BgtTokenInfo = _reflection.GeneratedProtocolMessageType('BgtTokenInfo', (_message.Message,), dict(
  DESCRIPTOR = _BGTTOKENINFO,
  __module__ = 'bgt_common.protobuf.smart_bgt_token_pb2'
  # @@protoc_insertion_point(class_scope:BgtTokenInfo)
  ))
_sym_db.RegisterMessage(BgtTokenInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
