# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cert_common/protobuf/x509_cert.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$cert_common/protobuf/x509_cert.proto\"0\n\x0cX509CertInfo\x12\x11\n\towner_key\x18\x01 \x01(\t\x12\r\n\x05xcert\x18\x02 \x01(\x0c\x42\x1c\n\x18sawtooth.config.protobufP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cert_common.protobuf.x509_cert_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030sawtooth.config.protobufP\001'
  _X509CERTINFO._serialized_start=40
  _X509CERTINFO._serialized_end=88
# @@protoc_insertion_point(module_scope)
